version: "3"
services:
  backend:
    build: src/backend
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sm1
      MYSQL_ROOT_PASSWORD: "Momomomo2"
