version: "3"
services:
  backend:
    environment:
      - ENV_TESTING=True
      - ENV_DEBUG=True
      - ENV_TESTDATABASE_URI=sqlite:///sqlalchemy_example.db
      - ENV_DATABASE_URI=mysql+pymysql://root:Momomomo2@db/sm1
      - ENV_LDAP_SERVER_URL=ldap://swtldap.cloudapp.net
      - ENV_LDAP_SERVER_PORT=389
      - ENV_LDAP_SERVER_PREFIX=SWTAD\
      - ENV_LDAP_BASE_DN=CN=Users,DC=ldap,DC=SWT,DC=com
      - ENV_LDAP_SEARCH_BASE=DC=ldap,DC=SWT,DC=com
      - ENV_LDAP_USE_SSL=False
      - ENV_LDAP_AUTHENTICATION=NTLM
    build: src/backend
    depends_on:
      - db
    restart: always
    ports:
      - "80:5000"
  db:
    image: mysql:latest
    volumes:
      - ./src/backend/database/dockerdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sm1
      MYSQL_ROOT_PASSWORD: Momomomo2
      MYSQL_USER: root
      MYSQL_PASSWORD: Momomomo2
